blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/yourusername/beside-rental-platform/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/yourusername/beside-rental-platform/security/advisories/new
    about: Report security vulnerabilities privately
  - name: 📖 Documentation
    url: https://github.com/yourusername/beside-rental-platform#readme
    about: Check our comprehensive documentation
