// Item data and utility functions for item access

// TypeScript type for an item
export type Item = {
  id: string;
  title: string;
  description: string;
  price: number;
  originalPrice?: number;
  location: string;
  category: string;
  subcategory?: string;
  images: string[];
  ownerEmail: string; // Reference to user by email
  availability: string;
  availableFrom: string;
  availableUntil: string;
  specifications: Record<string, string>;
  included: string[];
  rules: string[];
  features: string[];
  cancellationPolicy: string;
  deposit: number;
  minRentalDays: number;
  maxRentalDays: number;
  deliveryAvailable: boolean;
  pickupAvailable: boolean;
  instantBooking: boolean;
  bookedDates?: string[];
};

// Comprehensive item data with detailed information for each item
export const allItems: Record<string, Item> = {
  // --- Books ---
  "61": {
    id: "61",
    title: "Harry Potter and the Philosopher's Stone",
    description: "The first book in the Harry Potter series.",
    price: 40,
    location: "Andheri, Mumbai",
    category: "Books",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "ab@gmail.com",
    availability: "available-now",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-15",
    specifications: { Author: "J.K. Rowling", Genre: "Fiction" },
    included: ["Book"],
    rules: ["No folding pages", "Return clean"],
    features: ["Fiction","Children","Fantasy"],
    cancellationPolicy: "Flexible",
    deposit: 100,
    minRentalDays: 1,
    maxRentalDays: 10,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true,
    bookedDates: ["2025-06-05", "2025-06-06", "2025-06-07"]
  },
  "62": {
    id: "62",
    title: "The Immortals of Meluha",
    description: "A gripping mythological fiction novel.",
    price: 35,
    location: "Sector 15, Gurgaon",
    category: "Books",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "priya.patel@email.com",
    availability: "weekend",
    availableFrom: "2025-06-01",
    availableUntil: "2025-06-02",
    specifications: { Author: "Amish Tripathi", Genre: "Fiction" },
    included: ["Book"],
    rules: ["No water exposure", "Return clean"],
    features: ["Fiction","Mythology"],
    cancellationPolicy: "Flexible",
    deposit: 80,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "63": {
    id: "63",
    title: "Wings of Fire",
    description: "Autobiography of Dr. Kalam, former President of India.",
    price: 30,
    location: "Koramangala, Bangalore",
    category: "Books",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "rajesh.kumar@email.com",
    availability: "next-week",
    availableFrom: "2025-06-07",
    availableUntil: "2025-06-21",
    specifications: { Author: "A.P.J. Abdul Kalam", Genre: "Biography" },
    included: ["Book"],
    rules: ["No folding pages", "Return clean"],
    features: ["Biography","Inspiration"],
    cancellationPolicy: "Flexible",
    deposit: 60,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "64": {
    id: "64",
    title: "The Blue Umbrella",
    description: "A classic children's story set in the hills.",
    price: 20,
    location: "Powai, Mumbai",
    category: "Books",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "sneha.reddy@email.com",
    availability: "available-now",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-10",
    specifications: { Author: "Ruskin Bond", Genre: "Children" },
    included: ["Book"],
    rules: ["No tearing pages", "Return clean"],
    features: ["Children","Classic"],
    cancellationPolicy: "Flexible",
    deposit: 40,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "65": {
    id: "65",
    title: "Five Point Someone",
    description: "A humorous take on life at IIT.",
    price: 25,
    location: "Koramangala, Bangalore",
    category: "Books",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "ab@gmail.com",
    availability: "next-week",
    availableFrom: "2025-06-02",
    availableUntil: "2025-06-28",
    specifications: { Author: "Chetan Bhagat", Genre: "Fiction" },
    included: ["Book"],
    rules: ["No water exposure", "Return clean"],
    features: ["Fiction","Humor"],
    cancellationPolicy: "Flexible",
    deposit: 50,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "66": {
    id: "66",
    title: "The Da Vinci Code",
    description: "A thrilling mystery novel.",
    price: 50,
    location: "Connaught Place, Delhi",
    category: "Books",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "rajesh.kumar@email.com",
    availability: "weekend",
    availableFrom: "2025-05-31",
    availableUntil: "2025-06-01",
    specifications: { Author: "Dan Brown", Genre: "Fiction" },
    included: ["Book"],
    rules: ["No folding pages", "Return clean"],
    features: ["Fiction","Mystery"],
    cancellationPolicy: "Flexible",
    deposit: 100,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "67": {
    id: "67",
    title: "The Alchemist",
    description: "A philosophical story about following your dreams.",
    price: 30,
    location: "Banjara Hills, Hyderabad",
    category: "Books",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "ab@gmail.com",
    availability: "available-now",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-15",
    specifications: { Author: "Paulo Coelho", Genre: "Fiction" },
    included: ["Book"],
    rules: ["No folding pages", "Return clean"],
    features: ["Fiction","Philosophy"],
    cancellationPolicy: "Flexible",
    deposit: 60,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "68": {
    id: "68",
    title: "Sudha Murty's Grandparents' Bag of Stories",
    description: "A collection of heartwarming stories for children.",
    price: 20,
    location: "T. Nagar, Chennai",
    category: "Books",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "rajesh.kumar@email.com",
    availability: "next-week",
    availableFrom: "2025-06-02",
    availableUntil: "2025-06-23",
    specifications: { Author: "Sudha Murty", Genre: "Children" },
    included: ["Book"],
    rules: ["No tearing pages", "Return clean"],
    features: ["Children","Stories"],
    cancellationPolicy: "Flexible",
    deposit: 40,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "69": {
    id: "69",
    title: "Sapiens: A Brief History of Humankind",
    description: "A thought-provoking journey through human history.",
    price: 45,
    location: "Salt Lake, Kolkata",
    category: "Books",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "rajesh.kumar@email.com",
    availability: "available-now",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-20",
    specifications: { Author: "Yuval Noah Harari", Genre: "Non-Fiction" },
    included: ["Book"],
    rules: ["No folding pages", "Return clean"],
    features: ["Non-Fiction","History"],
    cancellationPolicy: "Flexible",
    deposit: 90,
    minRentalDays: 1,
    maxRentalDays: 10,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "70": {
    id: "70",
    title: "A Brief History of Time",
    description: "A landmark volume in science writing by one of the great minds of our time.",
    price: 50,
    location: "Gachibowli, Hyderabad",
    category: "Books",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "sneha.reddy@email.com",
    availability: "weekend",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-10",
    specifications: { Author: "Stephen Hawking", Genre: "Science" },
    included: ["Book"],
    rules: ["No folding pages", "Return clean"],
    features: ["Science","Physics"],
    cancellationPolicy: "Flexible",
    deposit: 100,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "71": {
    id: "71",
    title: "The Selfish Gene",
    description: "A classic exposition of evolutionary thought.",
    price: 40,
    location: "Viman Nagar, Pune",
    category: "Books",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "ab@gmail.com",
    availability: "available-now",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-18",
    specifications: { Author: "Richard Dawkins", Genre: "Science" },
    included: ["Book"],
    rules: ["No folding pages", "Return clean"],
    features: ["Science","Evolution"],
    cancellationPolicy: "Flexible",
    deposit: 80,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "72": {
    id: "72",
    title: "Tintin in Tibet",
    description: "A classic adventure from the beloved Tintin comics.",
    price: 30,
    location: "MG Road, Bengaluru",
    category: "Books",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "arjun.sharma@email.com",
    availability: "available-now",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-25",
    specifications: { Author: "Hergé", Genre: "Comics" },
    included: ["Book"],
    rules: ["No tearing pages", "Return clean"],
    features: ["Comics","Adventure"],
    cancellationPolicy: "Flexible",
    deposit: 60,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "73": {
    id: "73",
    title: "Batman: Year One",
    description: "The origin story of Batman in graphic novel form.",
    price: 35,
    location: "Churchgate, Mumbai",
    category: "Books",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "priya.patel@email.com",
    availability: "weekend",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-12",
    specifications: { Author: "Frank Miller", Genre: "Comics" },
    included: ["Book"],
    rules: ["No folding pages", "Return clean"],
    features: ["Comics","Graphic Novel"],
    cancellationPolicy: "Flexible",
    deposit: 70,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  // --- Electronics ---
  "1": {
    id: "1",
    title: "Professional DSLR Camera",
    description: "High-end Canon EOS R5 DSLR camera perfect for professional photography and videography. Includes multiple lenses, tripod, and all necessary accessories for stunning shots.",
    price: 500,
    location: "Andheri, Mumbai",
    category: "Electronics",
    subcategory: "camera",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "ab@gmail.com",
    availability: "available-now",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-15",
    specifications: { Brand: "Canon", Model: "EOS R5" },
    included: ["Camera Body", "Lenses", "Tripod", "Bag"],
    rules: ["Handle with care", "No water exposure"],
    features: ["45MP Full Frame","8K Video Recording","Dual Memory Slots","In-body Stabilization","Weather Sealing"],
    cancellationPolicy: "Flexible",
    deposit: 2000,
    minRentalDays: 1,
    maxRentalDays: 14,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true,
    bookedDates: ["2025-06-10", "2025-06-11", "2025-06-12", "2025-06-13", "2025-06-14"]
  },
  "2": {
    id: "2",
    title: "Gaming Laptop",
    description: "High-end gaming laptop with RTX 4070 graphics card, perfect for gaming, streaming, and heavy computational work. Features RGB keyboard and premium cooling system.",
    price: 800,
    location: "Sector 15, Gurgaon",
    category: "Electronics",
    subcategory: "laptop",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "priya.patel@email.com",
    availability: "weekend",
    availableFrom: "2025-06-01",
    availableUntil: "2025-06-02",
    specifications: { Brand: "ASUS", GPU: "RTX 4070" },
    included: ["Charger", "Laptop Bag"],
    rules: ["No food or drink near device"],
    features: ["RTX 4070 Graphics","144Hz Display","RGB Keyboard","Advanced Cooling","Thunderbolt 4"],
    cancellationPolicy: "Moderate",
    deposit: 3000,
    minRentalDays: 1,
    maxRentalDays: 10,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "3": {
    id: "3",
    title: "4K Projector",
    description: "Professional 4K projector with 3500 lumens brightness, perfect for presentations, movie nights, and events. Includes screen and sound system.",
    price: 700,
    location: "Koramangala, Bangalore",
    category: "Electronics",
    subcategory: "projector",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "rajesh.kumar@email.com",
    availability: "next-week",
    availableFrom: "2025-06-10",
    availableUntil: "2025-06-21",
    specifications: { Brand: "Sony", Resolution: "4K UHD" },
    included: ["Projector", "Remote", "Screen", "Sound System"],
    rules: ["No outdoor use", "Return all accessories"],
    features: ["4K Ultra HD","3500 Lumens","Wireless Connectivity","Portable Design","Long Lamp Life"],
    cancellationPolicy: "Flexible",
    deposit: 1500,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "4": {
    id: "4",
    title: "iPad Pro 12.9 inch",
    description: "Latest iPad Pro with M2 chip, perfect for digital art, productivity, and entertainment. Includes Apple Pencil (2nd Gen) and Magic Keyboard for complete workflow.",
    price: 400,
    location: "Powai, Mumbai",
    category: "Electronics",
    subcategory: "tablet",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "sneha.reddy@email.com",
    availability: "available-now",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-10",
    specifications: { Brand: "Apple", Model: "iPad Pro 12.9", Chip: "M2" },
    included: ["iPad Pro", "Apple Pencil", "Magic Keyboard"],
    rules: ["No food or drink near device"],
    features: ["Apple M2 Chip","Liquid Retina XDR Display","Apple Pencil Support","Magic Keyboard","Pro Camera System"],
    cancellationPolicy: "Flexible",
    deposit: 1000,
    minRentalDays: 1,
    maxRentalDays: 10,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "5": {
    id: "5",
    title: "MacBook Pro M3",
    description: "Latest MacBook Pro with M3 Pro chip, 16GB RAM, and 512GB SSD. Ideal for professional work, video editing, and development. Includes original charger and case.",
    price: 1000,
    location: "Koramangala, Bangalore",
    category: "Electronics",
    subcategory: "laptop",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "arjun.sharma@email.com",
    availability: "next-week",
    availableFrom: "2025-06-15",
    availableUntil: "2025-06-28",
    specifications: { Brand: "Apple", Model: "MacBook Pro M3 Pro", RAM: "16GB", Storage: "512GB SSD" },
    included: ["MacBook Pro", "Charger", "Case"],
    rules: ["No food or drink near device"],
    features: ["Apple M3 Pro","14-inch Liquid Retina XDR","All-day Battery","Silent Operation","Premium Build Quality"],
    cancellationPolicy: "Strict",
    deposit: 4000,
    minRentalDays: 2,
    maxRentalDays: 14,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "6": {
    id: "6",
    title: "PlayStation 5",
    description: "Sony PlayStation 5 console with 2 DualSense controllers and popular games included. Perfect for gaming sessions with friends and family.",
    price: 600,
    location: "Connaught Place, Delhi",
    category: "Electronics",
    subcategory: "console",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "sneha.reddy@email.com",
    availability: "weekend",
    availableFrom: "2025-05-31",
    availableUntil: "2025-06-01",
    specifications: { Brand: "Sony", Model: "PlayStation 5" },
    included: ["PS5 Console", "2 DualSense Controllers", "Games"],
    rules: ["No food or drink near device", "Return all accessories"],
    features: ["Ultra-fast SSD","4K Gaming at 120fps","Ray Tracing","3D Audio","Haptic Feedback"],
    cancellationPolicy: "Moderate",
    deposit: 2500,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "7": {
    id: "7",
    title: "iPhone 15 Pro",
    description: "Latest iPhone 15 Pro with 256GB storage, titanium design, and professional camera system. Perfect for photography, videography, and daily use.",
    price: 800,
    location: "Banjara Hills, Hyderabad",
    category: "Electronics",
    subcategory: "phone",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "arjun.sharma@email.com",
    availability: "available-now",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-15",
    specifications: { Brand: "Apple", Model: "iPhone 15 Pro", Storage: "256GB" },
    included: ["iPhone 15 Pro", "Charger", "Case"],
    rules: ["No water exposure", "Return with at least 50% battery"],
    features: ["48MP Pro Camera","Action Button","USB-C Connector","Always-On Display","Titanium Frame"],
    cancellationPolicy: "Flexible",
    deposit: 3000,
    minRentalDays: 1,
    maxRentalDays: 10,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "8": {
    id: "8",
    title: "Samsung Smart TV 65\"",
    description: "65-inch Samsung QLED 4K Smart TV with HDR support, built-in streaming apps, and premium sound system. Perfect for home entertainment and events.",
    price: 900,
    location: "T. Nagar, Chennai",
    category: "Electronics",
    subcategory: "tv",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "sneha.reddy@email.com",
    availability: "next-week",
    availableFrom: "2025-06-10",
    availableUntil: "2025-06-23",
    specifications: { Brand: "Samsung", Model: "QLED 65\"", Resolution: "4K HDR10+" },
    included: ["TV", "Remote", "Stand"],
    rules: ["No wall mounting", "Return remote"],
    features: ["65-inch QLED","4K HDR10+","Smart Tizen OS","20W Dolby Digital","Multiple HDMI Ports"],
    cancellationPolicy: "Moderate",
    deposit: 2000,
    minRentalDays: 2,
    maxRentalDays: 10,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "9": {
    id: "9",
    title: "Professional Drone",
    description: "DJI Mavic 3 Pro drone with 4K camera, perfect for aerial photography and videography. Includes multiple batteries and professional gimbal.",
    price: 900,
    location: "Cyber City, Gurgaon",
    category: "Electronics",
    subcategory: "drone",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "ab@gmail.com",
    availability: "next-week",
    availableFrom: "2025-06-05",
    availableUntil: "2025-06-19",
    specifications: { Brand: "DJI", Model: "Mavic 3 Pro" },
    included: ["Drone", "Batteries", "Gimbal", "Charger"],
    rules: ["No flying in restricted areas", "Return all accessories"],
    features: ["4K Hasselblad Camera","43min Flight Time","360° Obstacle Sensing","Professional Gimbal","Long Range"],
    cancellationPolicy: "Strict",
    deposit: 5000,
    minRentalDays: 1,
    maxRentalDays: 5,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "10": {
    id: "10",
    title: "JBL Party Speaker",
    description: "Powerful JBL PartyBox 710 with LED lights, perfect for parties, events, and gatherings. Features wireless connectivity and karaoke functionality.",
    price: 300,
    location: "Connaught Place, Delhi",
    category: "Electronics",
    subcategory: "speaker",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "arjun.sharma@email.com",
    availability: "weekend",
    availableFrom: "2025-05-31",
    availableUntil: "2025-06-01",
    specifications: { Brand: "JBL", Model: "PartyBox 710" },
    included: ["Speaker", "Wireless Microphones", "Power Cable"],
    rules: ["No outdoor use in rain", "Return all accessories"],
    features: ["800W RMS Sound","RGB LED Lights","18hr Battery Life","Wireless Microphones","Portable Design"],
    cancellationPolicy: "Flexible",
    deposit: 1000,
    minRentalDays: 1,
    maxRentalDays: 3,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  // --- Furniture ---
  "51": {
    id: "51",
    title: "3-Seater Sofa Set",
    description: "Comfortable sofa for living room",
    price: 600,
    location: "Koramangala, Bangalore",
    category: "Furniture",
    images: ["/placeholder.svg?height=300&width=400"],
    ownerEmail: "priya.patel@email.com",
    availability: "weekend",
    availableFrom: "2024-01-10",
    availableUntil: "2024-01-21",
    specifications: { Brand: "Urban Ladder", Type: "Sofa" },
    included: ["Sofa"],
    rules: ["No stains", "Return clean"],
    features: ["3-Seater","Fabric","Modern Design"],
    cancellationPolicy: "Flexible",
    deposit: 1000,
    minRentalDays: 1,
    maxRentalDays: 10,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "52": {
    id: "52",
    title: "Dining Table (6-Seater)",
    description: "Wooden dining table with chairs",
    price: 500,
    location: "Connaught Place, Delhi",
    category: "Furniture",
    images: ["/placeholder.svg?height=300&width=400"],
    ownerEmail: "ab@gmail.com",
    availability: "available-now",
    availableFrom: "2024-01-08",
    availableUntil: "2024-01-18",
    specifications: { Brand: "Godrej Interio", Type: "Dining Table" },
    included: ["Table", "6 Chairs"],
    rules: ["No scratches", "Return all chairs"],
    features: ["6-Seater","Wooden","Modern Design"],
    cancellationPolicy: "Moderate",
    deposit: 800,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "53": {
    id: "53",
    title: "Office Chair",
    description: "Ergonomic office chair",
    price: 200,
    location: "Banjara Hills, Hyderabad",
    category: "Furniture",
    images: ["/placeholder.svg?height=300&width=400"],
    ownerEmail: "arjun.sharma@email.com",
    availability: "next-week",
    availableFrom: "2024-01-12",
    availableUntil: "2024-01-25",
    specifications: { Brand: "Featherlite", Type: "Office Chair" },
    included: ["Chair"],
    rules: ["No stains", "Return clean"],
    features: ["Ergonomic","Adjustable Height","Wheels"],
    cancellationPolicy: "Flexible",
    deposit: 300,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "54": {
    id: "54",
    title: "Wardrobe",
    description: "3-door wardrobe with mirror",
    price: 400,
    location: "T. Nagar, Chennai",
    category: "Furniture",
    images: ["/placeholder.svg?height=300&width=400"],
    ownerEmail: "arjun.sharma@email.com",
    availability: "weekend",
    availableFrom: "2024-01-09",
    availableUntil: "2024-01-22",
    specifications: { Brand: "IKEA", Type: "Wardrobe" },
    included: ["Wardrobe"],
    rules: ["No stickers", "Return clean"],
    features: ["3-Door","Mirror","Spacious"],
    cancellationPolicy: "Flexible",
    deposit: 600,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "55": {
    id: "55",
    title: "King Size Bed",
    description: "Comfortable king size bed with mattress",
    price: 700,
    location: "Andheri, Mumbai",
    category: "Furniture",
    images: ["/placeholder.svg?height=300&width=400"],
    ownerEmail: "priya.patel@email.com",
    availability: "available-now",
    availableFrom: "2024-01-11",
    availableUntil: "2024-01-17",
    specifications: { Brand: "Sleepwell", Type: "Bed" },
    included: ["Bed", "Mattress"],
    rules: ["No stains", "Return mattress"],
    features: ["King Size","Mattress Included","Wooden Frame"],
    cancellationPolicy: "Strict",
    deposit: 1200,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "56": {
    id: "56",
    title: "Coffee Table",
    description: "Modern glass coffee table",
    price: 150,
    location: "Koramangala, Bangalore",
    category: "Furniture",
    images: ["/placeholder.svg?height=300&width=400"],
    ownerEmail: "ab@gmail.com",
    availability: "next-week",
    availableFrom: "2024-01-13",
    availableUntil: "2024-01-28",
    specifications: { Brand: "Pepperfry", Type: "Coffee Table" },
    included: ["Table"],
    rules: ["No scratches", "Return clean"],
    features: ["Glass Top","Modern Design","Lightweight"],
    cancellationPolicy: "Flexible",
    deposit: 200,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "57": {
    id: "57",
    title: "Bookshelf",
    description: "5-tier wooden bookshelf",
    price: 180,
    location: "Connaught Place, Delhi",
    category: "Furniture",
    images: ["/placeholder.svg?height=300&width=400"],
    ownerEmail: "priya.patel@email.com",
    availability: "weekend",
    availableFrom: "2024-01-05",
    availableUntil: "2024-01-19",
    specifications: { Brand: "IKEA", Type: "Bookshelf" },
    included: ["Bookshelf"],
    rules: ["No stickers", "Return clean"],
    features: ["5-Tier","Wooden","Modern Design"],
    cancellationPolicy: "Flexible",
    deposit: 250,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "58": {
    id: "58",
    title: "Recliner Chair",
    description: "Luxury leather recliner",
    price: 350,
    location: "Banjara Hills, Hyderabad",
    category: "Furniture",
    images: ["/placeholder.svg?height=300&width=400"],
    ownerEmail: "sneha.reddy@email.com",
    availability: "available-now",
    availableFrom: "2024-01-07",
    availableUntil: "2024-01-16",
    specifications: { Brand: "Urban Ladder", Type: "Recliner Chair" },
    included: ["Chair"],
    rules: ["No stains", "Return clean"],
    features: ["Leather","Recliner","Modern Design"],
    cancellationPolicy: "Flexible",
    deposit: 400,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "59": {
    id: "59",
    title: "Study Table",
    description: "Wooden study table with drawers",
    price: 220,
    location: "T. Nagar, Chennai",
    category: "Furniture",
    images: ["/placeholder.svg?height=300&width=400"],
    ownerEmail: "priya.patel@email.com",
    availability: "next-week",
    availableFrom: "2024-01-06",
    availableUntil: "2024-01-26",
    specifications: { Brand: "Godrej Interio", Type: "Study Table" },
    included: ["Table", "Drawers"],
    rules: ["No scratches", "Return clean"],
    features: ["Wooden","Drawers Included","Modern Design"],
    cancellationPolicy: "Flexible",
    deposit: 300,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "60": {
    id: "60",
    title: "Computer Desk",
    description: "Modern computer desk with cable management",
    price: 250,
    location: "Connaught Place, Delhi",
    category: "Furniture",
    images: ["/placeholder.svg?height=300&width=400"],
    ownerEmail: "arjun.sharma@email.com",
    availability: "weekend",
    availableFrom: "2024-01-13",
    availableUntil: "2024-01-20",
    specifications: { Brand: "IKEA", Type: "Computer Desk" },
    included: ["Desk"],
    rules: ["No stickers", "Return clean"],
    features: ["Cable Management","Modern Design","Wooden"],
    cancellationPolicy: "Flexible",
    deposit: 350,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  // --- Sports ---
  "21": {
    id: "21",
    title: "Adidas Football",
    description: "FIFA-approved match football, excellent grip and durability.",
    price: 200,
    location: "Mumbai, Maharashtra",
    category: "Sports",
    subcategory: "football",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "ab@gmail.com",
    availability: "available-now",
    availableFrom: "2025-05-20",
    availableUntil: "2025-06-30",
    specifications: { Brand: "Adidas", Type: "Football" },
    included: ["Football"],
    rules: ["No playing on concrete", "Return clean"],
    features: ["FIFA Approved","Size 5","Thermo-bonded"],
    cancellationPolicy: "Flexible",
    deposit: 500,
    minRentalDays: 1,
    maxRentalDays: 10,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "22": {
    id: "22",
    title: "Yonex Badminton Racket",
    description: "Lightweight graphite racket for professional play.",
    price: 150,
    location: "Delhi, Delhi",
    category: "Sports",
    subcategory: "badminton",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "rajesh.kumar@email.com",
    availability: "weekend",
    availableFrom: "2025-05-18",
    availableUntil: "2025-06-07",
    specifications: { Brand: "Yonex", Type: "Badminton Racket" },
    included: ["Racket", "Cover"],
    rules: ["No hitting on ground", "Return with cover"],
    features: ["Graphite","Ultra Light","Professional"],
    cancellationPolicy: "Moderate",
    deposit: 300,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "23": {
    id: "23",
    title: "SG Cricket Bat",
    description: "English willow cricket bat, ideal for tournaments.",
    price: 300,
    location: "Bangalore, Karnataka",
    category: "Sports",
    subcategory: "cricket",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "ab@gmail.com",
    availability: "next-week",
    availableFrom: "2025-05-15",
    availableUntil: "2025-07-10",
    specifications: { Brand: "SG", Type: "Cricket Bat" },
    included: ["Bat"],
    rules: ["No water exposure", "Return clean"],
    features: ["English Willow","Lightweight","Thick Edges"],
    cancellationPolicy: "Strict",
    deposit: 700,
    minRentalDays: 1,
    maxRentalDays: 14,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "24": {
    id: "24",
    title: "Cosco Table Tennis Set",
    description: "Complete set with 2 rackets and 3 balls.",
    price: 100,
    location: "Chennai, Tamil Nadu",
    category: "Sports",
    subcategory: "table-tennis",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "rajesh.kumar@email.com",
    availability: "available-now",
    availableFrom: "2025-05-22",
    availableUntil: "2025-06-20",
    specifications: { Brand: "Cosco", Type: "Table Tennis Set" },
    included: ["2 Rackets", "3 Balls"],
    rules: ["No outdoor play", "Return all items"],
    features: ["2 Rackets","3 Balls","Tournament Grade"],
    cancellationPolicy: "Flexible",
    deposit: 200,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "25": {
    id: "25",
    title: "Nivia Basketball",
    description: "Indoor/outdoor basketball, official size and weight.",
    price: 120,
    location: "Hyderabad, Telangana",
    category: "Sports",
    subcategory: "basketball",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "rajesh.kumar@email.com",
    availability: "weekend",
    availableFrom: "2025-05-10",
    availableUntil: "2025-06-14",
    specifications: { Brand: "Nivia", Type: "Basketball" },
    included: ["Basketball"],
    rules: ["No playing on rough surfaces", "Return clean"],
    features: ["Indoor/Outdoor","Official Size","Durable"],
    cancellationPolicy: "Moderate",
    deposit: 300,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "26": {
    id: "26",
    title: "Wilson Tennis Racket",
    description: "Wilson Pro Staff, used by professionals worldwide.",
    price: 250,
    location: "Pune, Maharashtra",
    category: "Sports",
    subcategory: "tennis",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "arjun.sharma@email.com",
    availability: "available-now",
    availableFrom: "2025-05-12",
    availableUntil: "2025-07-01",
    specifications: { Brand: "Wilson", Type: "Tennis Racket" },
    included: ["Racket", "Cover"],
    rules: ["No hitting on ground", "Return with cover"],
    features: ["Pro Staff","Graphite","Lightweight"],
    cancellationPolicy: "Flexible",
    deposit: 400,
    minRentalDays: 1,
    maxRentalDays: 10,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "27": {
    id: "27",
    title: "Spalding Baseball Bat",
    description: "Wooden baseball bat, league approved.",
    price: 180,
    location: "Ahmedabad, Gujarat",
    category: "Sports",
    subcategory: "baseball",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "ab@gmail.com",
    availability: "available-now",
    availableFrom: "2025-05-17",
    availableUntil: "2025-06-25",
    specifications: { Brand: "Spalding", Type: "Baseball Bat" },
    included: ["Bat"],
    rules: ["No water exposure", "Return clean"],
    features: ["Wooden","League Approved","Balanced"],
    cancellationPolicy: "Flexible",
    deposit: 300,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "28": {
    id: "28",
    title: "Hero Sprint Cycle",
    description: "Mountain bike, 21-speed, front suspension.",
    price: 350,
    location: "Surat, Gujarat",
    category: "Sports",
    subcategory: "cycle",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "arjun.sharma@email.com",
    availability: "weekend",
    availableFrom: "2025-05-21",
    availableUntil: "2025-06-08",
    specifications: { Brand: "Hero", Type: "Cycle" },
    included: ["Cycle", "Helmet"],
    rules: ["No stunts", "Return with helmet"],
    features: ["21-Speed","Front Suspension","Alloy Frame"],
    cancellationPolicy: "Moderate",
    deposit: 500,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "29": {
    id: "29",
    title: "GM Cricket Kit",
    description: "Complete cricket kit for all-rounders.",
    price: 500,
    location: "Lucknow, Uttar Pradesh",
    category: "Sports",
    subcategory: "cricket",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "priya.patel@email.com",
    availability: "available-now",
    availableFrom: "2025-05-19",
    availableUntil: "2025-06-30",
    specifications: { Brand: "GM", Type: "Cricket Kit" },
    included: ["Bat", "Pads", "Gloves", "Helmet", "Bag"],
    rules: ["Return all items", "No water exposure"],
    features: ["Bat, Pads, Gloves","Helmet","Bag Included"],
    cancellationPolicy: "Flexible",
    deposit: 1000,
    minRentalDays: 1,
    maxRentalDays: 14,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "30": {
    id: "30",
    title: "Nike Football Shoes",
    description: "High-grip football shoes for turf and grass.",
    price: 220,
    location: "Kanpur, Uttar Pradesh",
    category: "Sports",
    subcategory: "football-shoes",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "arjun.sharma@email.com",
    availability: "available-now",
    availableFrom: "2025-05-20",
    availableUntil: "2025-06-20",
    specifications: { Brand: "Nike", Type: "Football Shoes" },
    included: ["Shoes"],
    rules: ["No playing on concrete", "Return clean"],
    features: ["High Grip","Turf/Grass","Lightweight"],
    cancellationPolicy: "Flexible",
    deposit: 400,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  // --- Tools ---
  "31": {
    id: "31",
    title: "Cordless Drill Machine",
    description: "Powerful Bosch cordless drill for home and professional use. Includes multiple drill bits and carrying case.",
    price: 250,
    location: "Andheri, Mumbai",
    category: "Tools",
    subcategory: "drill",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "sneha.reddy@email.com",
    availability: "available-now",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-15",
    specifications: { Brand: "Bosch", Type: "Cordless Drill" },
    included: ["Drill", "Drill Bits", "Carrying Case"],
    rules: ["No water exposure", "Return all accessories"],
    features: ["18V Battery","2-Speed Gearbox","LED Light","Ergonomic Grip"],
    cancellationPolicy: "Flexible",
    deposit: 500,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "32": {
    id: "32",
    title: "Aluminum Ladder 12ft",
    description: "Sturdy 12ft aluminum ladder, lightweight and easy to transport. Ideal for painting, repairs, and maintenance.",
    price: 150,
    location: "Sector 15, Gurgaon",
    category: "Tools",
    subcategory: "ladder",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "priya.patel@email.com",
    availability: "weekend",
    availableFrom: "2025-06-01",
    availableUntil: "2025-06-02",
    specifications: { Brand: "JCB", Type: "Ladder", Height: "12ft" },
    included: ["Ladder"],
    rules: ["No overloading", "Return clean"],
    features: ["12ft Height","Anti-Slip Steps","Foldable","Lightweight"],
    cancellationPolicy: "Moderate",
    deposit: 300,
    minRentalDays: 1,
    maxRentalDays: 5,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "33": {
    id: "33",
    title: "Electric Circular Saw",
    description: "Makita circular saw for wood and metal cutting. Comes with safety guard and extra blades.",
    price: 300,
    location: "Koramangala, Bangalore",
    category: "Tools",
    subcategory: "saw",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "rajesh.kumar@email.com",
    availability: "next-week",
    availableFrom: "2025-06-07",
    availableUntil: "2025-06-21",
    specifications: { Brand: "Makita", Type: "Circular Saw" },
    included: ["Saw", "Safety Guard", "Extra Blades"],
    rules: ["No water exposure", "Return all accessories"],
    features: ["1200W Motor","Adjustable Base","Safety Guard","Extra Blades"],
    cancellationPolicy: "Strict",
    deposit: 700,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "34": {
    id: "34",
    title: "Digital Measuring Tape",
    description: "Stanley digital measuring tape for accurate measurements up to 30 meters. LCD display and memory function included.",
    price: 100,
    location: "Powai, Mumbai",
    category: "Tools",
    subcategory: "measuring",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "sneha.reddy@email.com",
    availability: "available-now",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-10",
    specifications: { Brand: "Stanley", Type: "Measuring Tape", Range: "30m" },
    included: ["Measuring Tape"],
    rules: ["No dropping", "Return with battery"],
    features: ["30m Range","LCD Display","Memory Function","Auto Shutoff"],
    cancellationPolicy: "Flexible",
    deposit: 200,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "35": {
    id: "35",
    title: "Heavy Duty Bolt Cutter",
    description: "Taparia heavy duty bolt cutter for cutting thick wires and bolts. Durable and easy to use.",
    price: 120,
    location: "Koramangala, Bangalore",
    category: "Tools",
    subcategory: "cutter",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "sneha.reddy@email.com",
    availability: "next-week",
    availableFrom: "2025-06-02",
    availableUntil: "2025-06-28",
    specifications: { Brand: "Taparia", Type: "Bolt Cutter", Length: "24-inch" },
    included: ["Bolt Cutter"],
    rules: ["No cutting hardened steel", "Return clean"],
    features: ["24-inch Length","Hardened Blades","Non-slip Grip"],
    cancellationPolicy: "Moderate",
    deposit: 300,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "36": {
    id: "36",
    title: "Precision Screwdriver Set",
    description: "Set of 32 precision screwdrivers for electronics and small appliances. Magnetic tips and ergonomic handles.",
    price: 80,
    location: "Connaught Place, Delhi",
    category: "Tools",
    subcategory: "screwdriver",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "priya.patel@email.com",
    availability: "weekend",
    availableFrom: "2025-05-31",
    availableUntil: "2025-06-01",
    specifications: { Brand: "Dewalt", Type: "Screwdriver Set", Pieces: "32" },
    included: ["32 Screwdrivers", "Case"],
    rules: ["No water exposure", "Return all pieces"],
    features: ["32 Pieces","Magnetic Tips","Ergonomic Handles"],
    cancellationPolicy: "Flexible",
    deposit: 100,
    minRentalDays: 1,
    maxRentalDays: 5,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "37": {
    id: "37",
    title: "Electric Jigsaw",
    description: "Hitachi electric jigsaw for wood and metal cutting. Variable speed and easy blade change.",
    price: 220,
    location: "Banjara Hills, Hyderabad",
    category: "Tools",
    subcategory: "jigsaw",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "priya.patel@email.com",
    availability: "available-now",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-15",
    specifications: { Brand: "Hitachi", Type: "Jigsaw" },
    included: ["Jigsaw", "Blades"],
    rules: ["No water exposure", "Return all blades"],
    features: ["Variable Speed","Quick Blade Change","Dust Blower"],
    cancellationPolicy: "Flexible",
    deposit: 300,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "38": {
    id: "38",
    title: "Multi-Tool Oscillating Tool",
    description: "Dewalt multi-tool for sanding, cutting, and scraping. Includes multiple attachments.",
    price: 260,
    location: "T. Nagar, Chennai",
    category: "Tools",
    subcategory: "multi-tool",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "ab@gmail.com",
    availability: "next-week",
    availableFrom: "2025-06-02",
    availableUntil: "2025-06-23",
    specifications: { Brand: "Dewalt", Type: "Oscillating Tool" },
    included: ["Oscillating Tool", "Attachments"],
    rules: ["No water exposure", "Return all attachments"],
    features: ["Multiple Attachments","Variable Speed","Compact Design"],
    cancellationPolicy: "Moderate",
    deposit: 400,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "39": {
    id: "39",
    title: "Pipe Wrench 18-inch",
    description: "Heavy-duty pipe wrench for plumbing and repair work. Adjustable jaw and sturdy build.",
    price: 90,
    location: "Cyber City, Gurgaon",
    category: "Tools",
    subcategory: "wrench",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "ab@gmail.com",
    availability: "next-week",
    availableFrom: "2025-06-05",
    availableUntil: "2025-06-19",
    specifications: { Brand: "Hilti", Type: "Pipe Wrench", Length: "18-inch" },
    included: ["Pipe Wrench"],
    rules: ["No water exposure", "Return clean"],
    features: ["18-inch Length","Adjustable Jaw","Heavy Duty"],
    cancellationPolicy: "Flexible",
    deposit: 100,
    minRentalDays: 1,
    maxRentalDays: 5,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "40": {
    id: "40",
    title: "Laser Level Tool",
    description: "Bosch laser level for accurate alignment in construction and interior work. Self-leveling and easy to use.",
    price: 350,
    location: "Connaught Place, Delhi",
    category: "Tools",
    subcategory: "laser-level",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "rajesh.kumar@email.com",
    availability: "weekend",
    availableFrom: "2025-05-31",
    availableUntil: "2025-06-01",
    specifications: { Brand: "Bosch", Type: "Laser Level" },
    included: ["Laser Level", "Tripod"],
    rules: ["No water exposure", "Return tripod"],
    features: ["Self-Leveling","High Visibility","Tripod Included"],
    cancellationPolicy: "Flexible",
    deposit: 500,
    minRentalDays: 1,
    maxRentalDays: 5,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  // --- Travel Gare ---
  "41": {
    id: "41",
    title: "Large Trolley Luggage",
    description: "Spacious 28-inch hard-shell trolley, lightweight and durable. Perfect for long trips.",
    price: 200,
    location: "Powai, Mumbai",
    category: "Travel Gare",
    subcategory: "luggage",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "ab@gmail.com",
    availability: "available-now",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-15",
    specifications: { Brand: "American Tourister", Type: "Luggage", Size: "28-inch" },
    included: ["Luggage"],
    rules: ["No overloading", "Return clean"],
    features: ["28-inch size","360° wheels","TSA lock","Expandable"],
    cancellationPolicy: "Flexible",
    deposit: 500,
    minRentalDays: 1,
    maxRentalDays: 10,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "42": {
    id: "42",
    title: "Wildcraft Backpack 45L",
    description: "Rugged 45L backpack with rain cover, ideal for trekking and travel.",
    price: 120,
    location: "Koramangala, Bangalore",
    category: "Travel Gare",
    subcategory: "backpack",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "rajesh.kumar@email.com",
    availability: "weekend",
    availableFrom: "2025-06-01",
    availableUntil: "2025-06-02",
    specifications: { Brand: "Wildcraft", Type: "Backpack", Capacity: "45L" },
    included: ["Backpack", "Rain Cover"],
    rules: ["No overloading", "Return rain cover"],
    features: ["45L capacity","Rain cover","Laptop sleeve","Multiple compartments"],
    cancellationPolicy: "Moderate",
    deposit: 200,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "43": {
    id: "43",
    title: "Universal Travel Adapter",
    description: "All-in-one travel adapter with USB ports, supports 150+ countries.",
    price: 50,
    location: "Connaught Place, Delhi",
    category: "Travel Gare",
    subcategory: "adapter",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "rajesh.kumar@email.com",
    availability: "next-week",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-10",
    specifications: { Brand: "AmazonBasics", Type: "Travel Adapter" },
    included: ["Adapter"],
    rules: ["No water exposure", "Return adapter"],
    features: ["4 USB ports","Surge protection","Compact design"],
    cancellationPolicy: "Flexible",
    deposit: 100,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "44": {
    id: "44",
    title: "Samsonite Cabin Luggage",
    description: "Premium 20-inch cabin luggage, lightweight and stylish. Fits most airlines.",
    price: 150,
    location: "Sector 15, Gurgaon",
    category: "Travel Gare",
    subcategory: "cabin-luggage",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "priya.patel@email.com",
    availability: "available-now",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-15",
    specifications: { Brand: "Samsonite", Type: "Cabin Luggage", Size: "20-inch" },
    included: ["Cabin Luggage"],
    rules: ["No overloading", "Return clean"],
    features: ["20-inch size","Lightweight","TSA lock"],
    cancellationPolicy: "Flexible",
    deposit: 300,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "45": {
    id: "45",
    title: "Travel Umbrella",
    description: "Windproof, compact travel umbrella. Easy to carry and quick-dry fabric.",
    price: 30,
    location: "Banjara Hills, Hyderabad",
    category: "Travel Gare",
    subcategory: "umbrella",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "sneha.reddy@email.com",
    availability: "weekend",
    availableFrom: "2025-05-31",
    availableUntil: "2025-06-01",
    specifications: { Brand: "Safari", Type: "Umbrella" },
    included: ["Umbrella"],
    rules: ["No strong winds", "Return dry"],
    features: ["Windproof","Quick-dry","Compact size"],
    cancellationPolicy: "Flexible",
    deposit: 50,
    minRentalDays: 1,
    maxRentalDays: 5,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "46": {
    id: "46",
    title: "GoPro Hero 12",
    description: "Action camera for travel vlogs and adventure. Includes mounts and waterproof case.",
    price: 250,
    location: "T. Nagar, Chennai",
    category: "Travel Gare",
    subcategory: "camera",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "priya.patel@email.com",
    availability: "next-week",
    availableFrom: "2025-06-02",
    availableUntil: "2025-06-23",
    specifications: { Brand: "GoPro", Type: "Action Camera" },
    included: ["Camera", "Mounts", "Waterproof Case"],
    rules: ["No water exposure without case", "Return all accessories"],
    features: ["4K video","Waterproof","Stabilization"],
    cancellationPolicy: "Moderate",
    deposit: 400,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "47": {
    id: "47",
    title: "VIP Soft Luggage Set",
    description: "Set of 2 soft luggage bags, lightweight and expandable. Great for family trips.",
    price: 300,
    location: "Andheri, Mumbai",
    category: "Travel Gare",
    subcategory: "luggage-set",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "sneha.reddy@email.com",
    availability: "available-now",
    availableFrom: "2025-06-03",
    availableUntil: "2025-06-20",
    specifications: { Brand: "VIP", Type: "Luggage Set" },
    included: ["2 Luggage Bags"],
    rules: ["No overloading", "Return both bags"],
    features: ["Set of 2","Expandable","Soft material"],
    cancellationPolicy: "Flexible",
    deposit: 600,
    minRentalDays: 1,
    maxRentalDays: 10,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "48": {
    id: "48",
    title: "Swiss Gear Laptop Backpack",
    description: "Travel backpack with padded laptop compartment and anti-theft design.",
    price: 140,
    location: "Kolkata",
    category: "Travel Gare",
    subcategory: "laptop-backpack",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "ab@gmail.com",
    availability: "next-week",
    availableFrom: "2025-06-04",
    availableUntil: "2025-06-18",
    specifications: { Brand: "Swiss Gear", Type: "Laptop Backpack" },
    included: ["Backpack"],
    rules: ["No overloading", "Return clean"],
    features: ["Anti-theft","Laptop sleeve","Ergonomic straps"],
    cancellationPolicy: "Flexible",
    deposit: 200,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  // --- Vehicles ---
  "11": {
    id: "11",
    title: "Honda City Sedan",
    description: "Comfortable Honda City sedan, automatic transmission, AC, and premium sound system. Perfect for city rides and outstation trips.",
    price: 1200,
    location: "Andheri, Mumbai",
    category: "Vehicles",
    subcategory: "car",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "ab@gmail.com",
    availability: "available-now",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-15",
    specifications: { Brand: "Honda", Model: "City" },
    included: ["Car", "Insurance"],
    rules: ["No smoking", "Return clean"],
    features: ["Automatic","AC","Premium Sound","Spacious"],
    cancellationPolicy: "Flexible",
    deposit: 3000,
    minRentalDays: 1,
    maxRentalDays: 10,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true,
    bookedDates: ["2025-06-08", "2025-06-09"]
  },
  "12": {
    id: "12",
    title: "Royal Enfield Classic 350",
    description: "Iconic Royal Enfield Classic 350 motorcycle, perfect for city and highway rides. Helmet included.",
    price: 500,
    location: "Koramangala, Bangalore",
    category: "Vehicles",
    subcategory: "bike",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "arjun.sharma@email.com",
    availability: "weekend",
    availableFrom: "2025-06-01",
    availableUntil: "2025-06-02",
    specifications: { Brand: "Royal Enfield", Model: "Classic 350" },
    included: ["Bike", "Helmet"],
    rules: ["No stunts", "Return with full tank"],
    features: ["350cc","Classic Design","Comfort Seat","ABS"],
    cancellationPolicy: "Moderate",
    deposit: 1500,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "13": {
    id: "13",
    title: "Maruti Suzuki Ertiga",
    description: "7-seater Maruti Suzuki Ertiga, ideal for family trips. Spacious, AC, and music system included.",
    price: 1800,
    location: "Connaught Place, Delhi",
    category: "Vehicles",
    subcategory: "car",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "rajesh.kumar@email.com",
    availability: "next-week",
    availableFrom: "2025-06-10",
    availableUntil: "2025-06-21",
    specifications: { Brand: "Maruti Suzuki", Model: "Ertiga" },
    included: ["Car", "Insurance"],
    rules: ["No pets", "Return clean"],
    features: ["7-Seater","AC","Music System","Spacious"],
    cancellationPolicy: "Flexible",
    deposit: 3500,
    minRentalDays: 2,
    maxRentalDays: 14,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "14": {
    id: "14",
    title: "Hyundai Creta SUV",
    description: "Hyundai Creta SUV, automatic, sunroof, and premium interiors. Great for city and highway drives.",
    price: 2200,
    location: "Powai, Mumbai",
    category: "Vehicles",
    subcategory: "suv",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "rajesh.kumar@email.com",
    availability: "available-now",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-10",
    specifications: { Brand: "Hyundai", Model: "Creta" },
    included: ["SUV", "Insurance"],
    rules: ["No off-roading", "Return clean"],
    features: ["Automatic","Sunroof","Premium Interiors","Spacious"],
    cancellationPolicy: "Strict",
    deposit: 4000,
    minRentalDays: 2,
    maxRentalDays: 10,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "15": {
    id: "15",
    title: "Tesla Model 3",
    description: "Tesla Model 3 electric sedan, Autopilot enabled, long-range battery.",
    price: 5000,
    location: "Gurgaon, Haryana",
    category: "Vehicles",
    subcategory: "car",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "arjun.sharma@email.com",
    availability: "weekend",
    availableFrom: "2025-06-01",
    availableUntil: "2025-06-14",
    specifications: { Brand: "Tesla", Model: "Model 3" },
    included: ["Car", "Charger"],
    rules: ["No smoking", "Return clean"],
    features: ["Electric", "Autopilot", "Long Range", "Premium Interior"],
    cancellationPolicy: "Strict",
    deposit: 8000,
    minRentalDays: 2,
    maxRentalDays: 10,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "16": {
    id: "16",
    title: "BMW X3 SUV",
    description: "Luxury BMW X3 SUV, comfortable and powerful, perfect for family trips. 2.0L diesel.",
    price: 3500,
    location: "Hyderabad, Telangana",
    category: "Vehicles",
    subcategory: "suv",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "sneha.reddy@email.com",
    availability: "next-week",
    availableFrom: "2025-06-10",
    availableUntil: "2025-07-01",
    specifications: { Brand: "BMW", Model: "X3" },
    included: ["SUV", "Insurance"],
    rules: ["No pets", "Return clean"],
    features: ["2.0L Diesel", "All-Wheel Drive", "Panoramic Sunroof", "Leather Seats"],
    cancellationPolicy: "Flexible",
    deposit: 6000,
    minRentalDays: 2,
    maxRentalDays: 14,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "17": {
    id: "17",
    title: "Kawasaki Ninja 650",
    description: "Sport motorcycle Kawasaki Ninja 650 with 649cc engine, agility and power combined.",
    price: 1500,
    location: "Chennai, Tamil Nadu",
    category: "Vehicles",
    subcategory: "bike",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "sneha.reddy@email.com",
    availability: "available-now",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-25",
    specifications: { Brand: "Kawasaki", Model: "Ninja 650" },
    included: ["Bike", "Helmet"],
    rules: ["No stunts", "Return with full tank"],
    features: ["649cc Engine", "Twin Chamber Exhaust", "LED Lighting", "ABS"],
    cancellationPolicy: "Moderate",
    deposit: 3000,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "18": {
    id: "18",
    title: "Ola S1 Pro Electric Scooter",
    description: "Ola S1 Pro electric scooter, high top speed and range, app connectivity.",
    price: 600,
    location: "Bengaluru, Karnataka",
    category: "Vehicles",
    subcategory: "scooter",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "arjun.sharma@email.com",
    availability: "weekend",
    availableFrom: "2025-06-08",
    availableUntil: "2025-06-20",
    specifications: { Brand: "Ola", Model: "S1 Pro" },
    included: ["Scooter", "Charger"],
    rules: ["No stunts", "Return with full charge"],
    features: ["AI-Powered", "App Control", "Range 90km", "Electric"],
    cancellationPolicy: "Flexible",
    deposit: 2000,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "19": {
    id: "19",
    title: "Tata Nexon EV",
    description: "Tata Nexon EV, compact electric SUV with great range and safety features.",
    price: 2500,
    location: "Pune, Maharashtra",
    category: "Vehicles",
    subcategory: "e-suv",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "priya.patel@email.com",
    availability: "available-now",
    availableFrom: "2025-05-30",
   
    availableUntil: "2025-06-30",
    specifications: { Brand: "Tata", Model: "Nexon EV" },
    included: ["SUV", "Charger"],
    rules: ["No off-roading", "Return with full charge"],
    features: ["Range 312km", "Fast Charging", "Climate Control", "Touchscreen Infotainment"],
    cancellationPolicy: "Flexible",
    deposit: 5000,
    minRentalDays: 2,
    maxRentalDays: 10,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
  "20": {
    id: "20",
    title: "Hero Splendor",
    description: "Hero Splendor commuter bike, fuel-efficient and reliable. 97.2cc engine.",
    price: 300,
    location: "Delhi, Delhi",
    category: "Vehicles",
    subcategory: "bike",
    images: ["/placeholder.svg?height=400&width=600"],
    ownerEmail: "rajesh.kumar@email.com",
    availability: "available-now",
    availableFrom: "2025-05-30",
    availableUntil: "2025-06-20",
    specifications: { Brand: "Hero", Model: "Splendor" },
    included: ["Bike", "Helmet"],
    rules: ["No stunts", "Return with full tank"],
    features: ["97.2cc Engine", "Telescopic Fork", "CBS", "Fuel Efficiency"],
    cancellationPolicy: "Flexible",
    deposit: 1000,
    minRentalDays: 1,
    maxRentalDays: 7,
    deliveryAvailable: true,
    pickupAvailable: true,
    instantBooking: true
  },
};

export function getAllItems(): Item[] {
  return Object.values(allItems);
}

export function getItemById(id: string): Item | null {
  return allItems[id] || null;
}

export function getItemsByOwner(ownerEmail: string) {
  return Object.values(allItems).filter(item => item.ownerEmail === ownerEmail);
}

export function updateItemBookedDates(itemId: string, dates: string[]) {
  if (allItems[itemId]) {
    allItems[itemId].bookedDates = dates;
  }
}
